#!/bin/bash
set -e
source ./.common

sudo su -p <<HERE
set -e
source ~/.bash_profile

# Python version
pip install --upgrade pip==$PIP_VERSION

# Extract project
if [ -f $PROJECT_DIR/db.sqlite3 ]; then
  yes | cp -rf $PROJECT_DIR/db.sqlite3 /home/ec2-user
fi
rm -rf $PROJECT_DIR
mkdir $PROJECT_DIR
tar -xzf /home/ec2-user/$PROJECT_NAME.tar.gz -C $PROJECT_DIR
if [ -f /home/ec2-user/db.sqlite3 ]; then
  yes | mv -f /home/ec2-user/db.sqlite3 $PROJECT_DIR
fi

# Copy files
yes | cp -rf $PROJECT_DIR/deploy/nginx.conf /etc/nginx
yes | cp -rf $PROJECT_DIR/deploy/uwsgi.ini /etc/uwsgi
yes | cp -rf $PROJECT_DIR/deploy/uwsgi /etc/init.d
HERE
