#!/bin/bash
set -e
source ./.common

sudo su -p <<HERE
set -e
source ~/.bash_profile

# pip
pip install -r $PROJECT_DIR/requirements.txt
pip install -r $PROJECT_DIR/requirements-aws.txt

# migrations
cd $PROJECT_DIR
python manage.py migrate --settings=$SETTINGS_NAMESPACE
python manage.py collectstatic --noinput --settings=$SETTINGS_NAMESPACE

# permissions
find $WEB_ROOT -type d -exec sudo chmod 2775 {} +
find $WEB_ROOT -type f -exec sudo chmod 0664 {} +
find $WEB_ROOT -type d -exec sudo chown www-data:www-data {} +
find $WEB_ROOT -type f -exec sudo chown www-data:www-data {} +
find /var/lib/nginx -type d -exec sudo chown www-data:www-data {} +

# service restart
service uwsgi restart
service nginx restart
HERE
